Correct Two Differences In The Sanity Test for 'pylint' (#129)
Correct Two Differences In The Sanity Test for 'pylint'

SUMMARY
Cleans up 2 of the 4 failures in the 'pylint' test under Python 3.8 that is currently failing in CI.
Validated locally with podman via the quay.io/ansible/network-ee-sanity-tests:latest like Zuul is running.
ISSUE TYPE

Bugfix Pull Request

COMPONENT NAME
quay.io/ansible/network-ee-sanity-tests:latest
ADDITIONAL INFORMATION


Running sanity test 'pylint' with Python 3.8
ERROR: Found 4 pylint issue(s) which need to be resolved:
ERROR: plugins/cliconf/asa.py:101:4: arguments-renamed: Parameter 'flags' has been renamed to 'format' in overridden 'Cliconf.get_config' method
ERROR: plugins/cliconf/asa.py:101:4: arguments-renamed: Parameter 'format' has been renamed to 'flags' in overridden 'Cliconf.get_config' method
The 'Cliconf.get_config' method is an abstract method so we might as well mirror the keyword argument ordering.
$ grep -r '.get_config('
plugins/cliconf/asa.py:    def get_config(self, source="running", flags=None, format="text"):
plugins/module_utils/network/asa/asa.py:def get_config(module, flags=None):
plugins/module_utils/network/asa/providers/module.py:        current_config = self.connection.get_config(flags=config_filter)
plugins/modules/asa_acl.py:        contents = get_config(module)
plugins/modules/asa_config.py:            contents = get_config(module)
plugins/modules/asa_config.py:        result["__backup__"] = get_config(module)
plugins/modules/asa_og.py:    sh_run_group_name = get_config(
plugins/modules/asa_og.py:    sh_run_group_type = get_config(
These calls to 'get_config' are easily traceable to the 'get_config' defined in 'plugins/module_utils/network/asa/asa.py':

plugins/module_utils/network/asa/providers/module.py
plugins/modules/asa_acl.py
plugins/modules/asa_og.py

from ansible_collections.cisco.asa.plugins.module_utils.network.asa.asa import (
    get_config,
    load_config,
)
The 'get_config' call in 'plugins/module_utils/network/asa/providers/module.py' is the only one I'm not certain on. I could see how via the Connection object it would come back the new 'Cliconf' based approach. Even if that's true though it specifies it's argument by keyword and would be unaffected by an ordering change.

Reviewed-by: Nathaniel Case <this.is@nathanielca.se>
Reviewed-by: Nilashish Chakraborty <nilashishchakraborty8@gmail.com>
Reviewed-by: None <None>